### ISSUE TITLE
dbt version 0.17.2 -  dbt found two macros with the name "test_unique" in the namespace "dbt"

### ISSUE THREAD

**Issue by vensyd** [mikaelene/dbt-sqlserver#42]
Getting below issue: 

```
c:\DV_Demo>dbt test
Running with dbt=0.17.2
* Deprecation Warning: dbt v0.17.0 introduces a new config format for the
dbt_project.yml file. Support for the existing version 1 format will be removed
in a future release of dbt. The following packages are currently configured with
config version 1:
 - dbt_sqlserver

For upgrading instructions, consult the documentation:
  https://docs.getdbt.com/docs/guides/migration-guide/upgrading-to-0-17-0
Encountered an error:
Compilation Error
  dbt found two macros with the name "test_unique" in the namespace "dbt". Since these macros have the same name and exist in the same namespace, dbt will be unable to decide which to call. To fix this, change the name of one of these macros:
  - macro.dbt_sqlserver.test_unique (macros\schema_tests.sql)
  - macro.dbt_sqlserver.test_unique (macros\schema_tests.sql)
```
**Version check:**

```
c:\DV_Demo>dbt --version
installed version: 0.17.2
   latest version: 0.17.2

Up to date!

Plugins:
  - postgres: 0.17.2
  - redshift: 0.17.2
  - snowflake: 0.17.2
```
Was working with 0.15.2 after --upgrade dbt getting this issue.

**Comment by swanderz** [comment]
known issue check out. #16. we're waiting for `0.18.0` to be released

**Comment by mikaelene** [comment]
Yes as @swanderz says, 0.16 and higher are not supported.
